import java.util.*;

public class TestScript {
    public static void main(String[] args) {
        System.out.println("Warehouse Management System - Test Script");
        System.out.println("========================================");
        System.out.println();
        
        // This script demonstrates the required test sequence
        System.out.println("Follow these steps to test the system:");
        System.out.println();
        System.out.println("1. Compile the program:");
        System.out.println("   javac *.java");
        System.out.println();
        System.out.println("2. Run the program:");
        System.out.println("   java UserInterface");
        System.out.println();
        System.out.println("3. Perform the following operations through the menu:");
        System.out.println();
        System.out.println("   a) Create five clients (C1 through C5)");
        System.out.println("      - Select option 1 five times");
        System.out.println("      - Enter names, addresses, and phone numbers for each client");
        System.out.println();
        System.out.println("   b) Display all clients");
        System.out.println("      - Select option 2");
        System.out.println("      - Note the initial balance of $0.00 for each client");
        System.out.println();
        System.out.println("   c) Create five products (P1 through P5)");
        System.out.println("      - Select option 3 five times");
        System.out.println("      - P1: Quantity 10, Price $1.00");
        System.out.println("      - P2: Quantity 20, Price $2.00");
        System.out.println("      - P3: Quantity 30, Price $3.00");
        System.out.println("      - P4: Quantity 40, Price $4.00");
        System.out.println("      - P5: Quantity 50, Price $5.00");
        System.out.println();
        System.out.println("   d) Display all products");
        System.out.println("      - Select option 4");
        System.out.println("      - Verify quantities and prices");
        System.out.println();
        System.out.println("   e) Add items to C1's wishlist");
        System.out.println("      - Select option 5");
        System.out.println("      - Enter client ID: C1");
        System.out.println("      - Add: 5 units of P1, P3, and P5");
        System.out.println();
        System.out.println("   f) Display C1's wishlist");
        System.out.println("      - Select option 6");
        System.out.println("      - Enter client ID: C1");
        System.out.println();
        System.out.println("   g) Add items to C2's wishlist");
        System.out.println("      - Select option 5");
        System.out.println("      - Enter client ID: C2");
        System.out.println("      - Add: 7 units of P1, P2, and P4");
        System.out.println();
        System.out.println("   h) Display C2's wishlist");
        System.out.println("      - Select option 6");
        System.out.println("      - Enter client ID: C2");
        System.out.println();
        System.out.println("   i) Add items to C3's wishlist");
        System.out.println("      - Select option 5");
        System.out.println("      - Enter client ID: C3");
        System.out.println("      - Add: 6 units of P1, P2, and P5");
        System.out.println();
        System.out.println("   j) Display C3's wishlist");
        System.out.println("      - Select option 6");
        System.out.println("      - Enter client ID: C3");
        System.out.println();
        System.out.println("   k) Place order for C2");
        System.out.println("      - Select option 7");
        System.out.println("      - Enter client ID: C2");
        System.out.println("      - This will process all items in C2's wishlist");
        System.out.println();
        System.out.println("   l) Display all clients");
        System.out.println("      - Select option 2");
        System.out.println("      - Note updated balances for C2");
        System.out.println();
        System.out.println("   m) Place order for C3");
        System.out.println("      - Select option 7");
        System.out.println("      - Enter client ID: C3");
        System.out.println();
        System.out.println("   n) Display all clients");
        System.out.println("      - Select option 2");
        System.out.println("      - Note updated balances for C3");
        System.out.println();
        System.out.println("   o) Display C2's wishlist");
        System.out.println("      - Select option 6");
        System.out.println("      - Enter client ID: C2");
        System.out.println();
        System.out.println("   p) Display C3's wishlist");
        System.out.println("      - Select option 6");
        System.out.println("      - Enter client ID: C3");
        System.out.println();
        System.out.println("   q) Display P1's waitlist");
        System.out.println("      - Select option 10");
        System.out.println("      - Enter product SKU: P1");
        System.out.println();
        System.out.println("   r) Display P2's waitlist");
        System.out.println("      - Select option 10");
        System.out.println("      - Enter product SKU: P2");
        System.out.println();
        System.out.println("   s) Place order for C1");
        System.out.println("      - Select option 7");
        System.out.println("      - Enter client ID: C1");
        System.out.println();
        System.out.println("   t) Display all clients");
        System.out.println("      - Select option 2");
        System.out.println("      - Note updated balances for C1");
        System.out.println();
        System.out.println("   u) Display C1's wishlist");
        System.out.println("      - Select option 6");
        System.out.println("      - Enter client ID: C1");
        System.out.println();
        System.out.println("   v) Record payments for C1 and C2");
        System.out.println("      - Select option 8");
        System.out.println("      - Enter client ID: C1");
        System.out.println("      - Enter amount: 100");
        System.out.println("      - Select option 8 again");
        System.out.println("      - Enter client ID: C2");
        System.out.println("      - Enter amount: 100");
        System.out.println();
        System.out.println("   w) Display all clients");
        System.out.println("      - Select option 2");
        System.out.println("      - Note updated balances after payments");
        System.out.println();
        System.out.println("   x) Receive shipment of 100 units of P1");
        System.out.println("      - Select option 9");
        System.out.println("      - Enter product SKU: P1");
        System.out.println("      - Enter quantity: 100");
        System.out.println("      - This will fulfill waitlist items for P1");
        System.out.println();
        System.out.println("   y) Display all products");
        System.out.println("      - Select option 4");
        System.out.println("      - Note updated quantity for P1");
        System.out.println();
        System.out.println("   z) Display all clients");
        System.out.println("      - Select option 2");
        System.out.println("      - Note any balance changes from waitlist fulfillment");
        System.out.println();
        System.out.println("   aa) Display invoices for C1");
        System.out.println("      - Select option 11");
        System.out.println("      - Enter client ID: C1");
        System.out.println();
        System.out.println("   ab) Display invoices for C2");
        System.out.println("      - Select option 11");
        System.out.println("      - Enter client ID: C2");
    }
}